<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Activity;

class ActivitiesTableSeeder extends Seeder
{
    public function run(): void
    {
        $activities = [
            // Byblos additions
            [
                'name' => 'Explore Byblos Archaeological Area',
                'city' => 'byblos',
                'category' => 'historical',
                'description' => 'A cultural stop around the archaeological remains with old stones, history, and open sea views nearby.',
                'location' => 'Byblos Archaeological Site',
                'best_time' => 'morning',
                'duration_estimate' => '1-2 hours',
                'price_type' => 'medium',
                'vibe_tags' => ['cultural', 'scenic', 'casual'],
                'occasion_tags' => ['friends', 'family', 'casual'],
            ],
            [
                'name' => 'Byblos Harbor Café Break',
                'city' => 'byblos',
                'category' => 'food',
                'description' => 'A relaxed harbor-side stop for coffee, light food, and a calm coastal atmosphere.',
                'location' => 'Byblos Harbor',
                'best_time' => 'afternoon',
                'duration_estimate' => '1 hour',
                'price_type' => 'low',
                'vibe_tags' => ['cozy', 'relaxing', 'seaside'],
                'occasion_tags' => ['friends', 'date', 'casual'],
            ],
            [
                'name' => 'Byblos Marina Evening Walk',
                'city' => 'byblos',
                'category' => 'scenic',
                'description' => 'An easy evening walk by the marina with lights, sea views, and a soft coastal mood.',
                'location' => 'Byblos Marina',
                'best_time' => 'evening',
                'duration_estimate' => '1 hour',
                'price_type' => 'free',
                'vibe_tags' => ['relaxing', 'romantic', 'scenic'],
                'occasion_tags' => ['date', 'friends', 'casual'],
            ],

            // Beirut additions
            [
                'name' => 'Visit the National Museum of Beirut',
                'city' => 'beirut',
                'category' => 'cultural',
                'description' => 'A strong cultural stop to explore Lebanese history, archaeology, and important artifacts.',
                'location' => 'National Museum of Beirut',
                'best_time' => 'afternoon',
                'duration_estimate' => '1-2 hours',
                'price_type' => 'medium',
                'vibe_tags' => ['cultural', 'casual'],
                'occasion_tags' => ['friends', 'family', 'casual'],
            ],
            [
                'name' => 'Zaitunay Bay Sunset Walk',
                'city' => 'beirut',
                'category' => 'scenic',
                'description' => 'A polished waterfront walk with marina views and one of the nicer sunset moments in Beirut.',
                'location' => 'Zaitunay Bay',
                'best_time' => 'sunset',
                'duration_estimate' => '1 hour',
                'price_type' => 'free',
                'vibe_tags' => ['sunset', 'scenic', 'romantic'],
                'occasion_tags' => ['date', 'casual'],
            ],
            [
                'name' => 'Hamra Street Walk',
                'city' => 'beirut',
                'category' => 'city',
                'description' => 'Explore a lively Beirut street with cafés, shops, and a casual urban atmosphere.',
                'location' => 'Hamra',
                'best_time' => 'evening',
                'duration_estimate' => '1-2 hours',
                'price_type' => 'free',
                'vibe_tags' => ['city', 'lively', 'casual'],
                'occasion_tags' => ['friends', 'casual', 'business'],
            ],

            // Batroun additions
            [
                'name' => 'Batroun Harbor Morning Walk',
                'city' => 'batroun',
                'category' => 'walking',
                'description' => 'A calm early walk around the harbor with fishing boats, sea air, and a peaceful coastal mood.',
                'location' => 'Batroun Harbor',
                'best_time' => 'morning',
                'duration_estimate' => '45 minutes',
                'price_type' => 'free',
                'vibe_tags' => ['relaxing', 'seaside', 'casual'],
                'occasion_tags' => ['friends', 'family', 'casual'],
            ],
            [
                'name' => 'Explore Batroun Phoenician Wall',
                'city' => 'batroun',
                'category' => 'historical',
                'description' => 'A short historical stop to enjoy one of Batroun’s most recognizable heritage spots near the sea.',
                'location' => 'Batroun Phoenician Wall Area',
                'best_time' => 'morning',
                'duration_estimate' => '45 minutes',
                'price_type' => 'free',
                'vibe_tags' => ['cultural', 'scenic', 'casual'],
                'occasion_tags' => ['friends', 'family', 'casual'],
            ],
            [
                'name' => 'Batroun Rooftop Evening',
                'city' => 'batroun',
                'category' => 'nightlife',
                'description' => 'A light nightlife option with music, drinks, and a lively evening atmosphere near the coast.',
                'location' => 'Batroun Rooftop District',
                'best_time' => 'evening',
                'duration_estimate' => '2 hours',
                'price_type' => 'medium',
                'vibe_tags' => ['lively', 'fun', 'nightlife'],
                'occasion_tags' => ['friends', 'night-out'],
            ],

            // Tripoli additions
            [
                'name' => 'Visit Tripoli Citadel',
                'city' => 'tripoli',
                'category' => 'historical',
                'description' => 'A major historical stop with old stone architecture, elevated views, and a classic Tripoli feel.',
                'location' => 'Tripoli Citadel',
                'best_time' => 'morning',
                'duration_estimate' => '1-2 hours',
                'price_type' => 'medium',
                'vibe_tags' => ['cultural', 'historical', 'scenic'],
                'occasion_tags' => ['friends', 'family', 'casual'],
            ],
            [
                'name' => 'Al Mina Seafront Walk',
                'city' => 'tripoli',
                'category' => 'scenic',
                'description' => 'A relaxed coastal walk in Al Mina with open views and a more laid-back side of Tripoli.',
                'location' => 'Al Mina',
                'best_time' => 'sunset',
                'duration_estimate' => '1 hour',
                'price_type' => 'free',
                'vibe_tags' => ['relaxing', 'sunset', 'seaside'],
                'occasion_tags' => ['date', 'friends', 'casual'],
            ],
            [
                'name' => 'Explore a Hidden Tripoli Alley',
                'city' => 'tripoli',
                'category' => 'hidden_gem',
                'description' => 'Discover a quieter part of Tripoli with local details, older streets, and a less touristy feel.',
                'location' => 'Tripoli Old Quarter',
                'best_time' => 'afternoon',
                'duration_estimate' => '1 hour',
                'price_type' => 'free',
                'vibe_tags' => ['hidden_gem', 'cultural', 'casual'],
                'occasion_tags' => ['friends', 'casual'],
            ],

            // Tyre additions
            [
                'name' => 'Tyre Old City Walk',
                'city' => 'tyre',
                'category' => 'historical',
                'description' => 'A cultural walk through older streets and landmarks for a classic Tyre atmosphere.',
                'location' => 'Tyre Old City',
                'best_time' => 'morning',
                'duration_estimate' => '1-2 hours',
                'price_type' => 'free',
                'vibe_tags' => ['cultural', 'casual', 'scenic'],
                'occasion_tags' => ['friends', 'family', 'casual'],
            ],
            [
                'name' => 'Relax at Tyre Beach',
                'city' => 'tyre',
                'category' => 'beach',
                'description' => 'Spend a laid-back afternoon by the sea with sand, sun, and a calm coastal vibe.',
                'location' => 'Tyre Beach',
                'best_time' => 'afternoon',
                'duration_estimate' => '2-3 hours',
                'price_type' => 'low',
                'vibe_tags' => ['beach', 'relaxing', 'seaside'],
                'occasion_tags' => ['friends', 'family', 'casual'],
            ],
            [
                'name' => 'Tyre Harbor Sunset Walk',
                'city' => 'tyre',
                'category' => 'scenic',
                'description' => 'A calm sunset walk near the harbor with open sea views and a romantic coastal feel.',
                'location' => 'Tyre Harbor',
                'best_time' => 'sunset',
                'duration_estimate' => '1 hour',
                'price_type' => 'free',
                'vibe_tags' => ['sunset', 'romantic', 'seaside'],
                'occasion_tags' => ['date', 'casual'],
            ],

            // Jounieh additions
            [
                'name' => 'Jounieh Bay Walk',
                'city' => 'jounieh',
                'category' => 'walking',
                'description' => 'An easy coastal walk around the bay with sea views and a lively Jounieh atmosphere.',
                'location' => 'Jounieh Bay',
                'best_time' => 'morning',
                'duration_estimate' => '1 hour',
                'price_type' => 'free',
                'vibe_tags' => ['seaside', 'relaxing', 'casual'],
                'occasion_tags' => ['friends', 'family', 'casual'],
            ],
            [
                'name' => 'Harissa Scenic Stop',
                'city' => 'jounieh',
                'category' => 'scenic',
                'description' => 'A scenic stop for elevated views over Jounieh and a memorable mountain-to-sea perspective.',
                'location' => 'Harissa',
                'best_time' => 'afternoon',
                'duration_estimate' => '1 hour',
                'price_type' => 'medium',
                'vibe_tags' => ['scenic', 'cultural', 'romantic'],
                'occasion_tags' => ['date', 'friends', 'family'],
            ],
            [
                'name' => 'Jounieh Evening Strip Walk',
                'city' => 'jounieh',
                'category' => 'nightlife',
                'description' => 'A lively evening experience around cafés, music spots, and the energetic Jounieh coast.',
                'location' => 'Jounieh Seafront',
                'best_time' => 'evening',
                'duration_estimate' => '2 hours',
                'price_type' => 'low',
                'vibe_tags' => ['lively', 'fun', 'nightlife'],
                'occasion_tags' => ['friends', 'night-out'],
            ],

            // Saida additions
            [
                'name' => 'Saida Old Souk Walk',
                'city' => 'saida',
                'category' => 'cultural',
                'description' => 'A traditional walk through the souk with local shops, older streets, and everyday city character.',
                'location' => 'Saida Old Souk',
                'best_time' => 'morning',
                'duration_estimate' => '1-2 hours',
                'price_type' => 'free',
                'vibe_tags' => ['cultural', 'casual'],
                'occasion_tags' => ['friends', 'family', 'casual'],
            ],
            [
                'name' => 'Visit Saida Sea Castle',
                'city' => 'saida',
                'category' => 'historical',
                'description' => 'A historical stop by the water with heritage value, sea views, and strong photo potential.',
                'location' => 'Saida Sea Castle',
                'best_time' => 'afternoon',
                'duration_estimate' => '1 hour',
                'price_type' => 'medium',
                'vibe_tags' => ['historical', 'scenic', 'cultural'],
                'occasion_tags' => ['friends', 'family', 'casual'],
            ],
            [
                'name' => 'Saida Corniche Sunset Walk',
                'city' => 'saida',
                'category' => 'scenic',
                'description' => 'A soft seaside walk at sunset with open views and a relaxed South Lebanon coastal mood.',
                'location' => 'Saida Corniche',
                'best_time' => 'sunset',
                'duration_estimate' => '1 hour',
                'price_type' => 'free',
                'vibe_tags' => ['sunset', 'relaxing', 'seaside'],
                'occasion_tags' => ['date', 'friends', 'casual'],
            ],

            // Broumana additions
            [
                'name' => 'Broumana Pine Walk',
                'city' => 'broumana',
                'category' => 'walking',
                'description' => 'A fresh mountain-area walk with trees, cleaner air, and a calm Broumana atmosphere.',
                'location' => 'Broumana Main Road Area',
                'best_time' => 'morning',
                'duration_estimate' => '1 hour',
                'price_type' => 'free',
                'vibe_tags' => ['relaxing', 'scenic', 'casual'],
                'occasion_tags' => ['friends', 'family', 'casual'],
            ],
            [
                'name' => 'Broumana Café Terrace Break',
                'city' => 'broumana',
                'category' => 'food',
                'description' => 'A cozy stop on a terrace for coffee, light food, and a cooler mountain-town vibe.',
                'location' => 'Broumana Center',
                'best_time' => 'afternoon',
                'duration_estimate' => '1 hour',
                'price_type' => 'low',
                'vibe_tags' => ['cozy', 'relaxing', 'casual'],
                'occasion_tags' => ['friends', 'date', 'casual'],
            ],
            [
                'name' => 'Broumana Evening Stroll',
                'city' => 'broumana',
                'category' => 'city',
                'description' => 'A simple evening walk through Broumana for lights, cafés, and a relaxed social atmosphere.',
                'location' => 'Broumana Main Street',
                'best_time' => 'evening',
                'duration_estimate' => '1 hour',
                'price_type' => 'free',
                'vibe_tags' => ['cozy', 'city', 'casual'],
                'occasion_tags' => ['friends', 'casual'],
            ],

            // Zahle additions
            [
                'name' => 'Zahle Riverside Walk',
                'city' => 'zahle',
                'category' => 'walking',
                'description' => 'A relaxed walk by the river with local energy, open-air seating, and a classic Zahle feel.',
                'location' => 'Berdawni Area',
                'best_time' => 'morning',
                'duration_estimate' => '1 hour',
                'price_type' => 'free',
                'vibe_tags' => ['relaxing', 'casual', 'scenic'],
                'occasion_tags' => ['friends', 'family', 'casual'],
            ],
            [
                'name' => 'Explore Zahle Old Streets',
                'city' => 'zahle',
                'category' => 'cultural',
                'description' => 'A cultural walk through older parts of Zahle with local charm and a slower atmosphere.',
                'location' => 'Old Zahle',
                'best_time' => 'afternoon',
                'duration_estimate' => '1-2 hours',
                'price_type' => 'free',
                'vibe_tags' => ['cultural', 'casual', 'hidden_gem'],
                'occasion_tags' => ['friends', 'casual'],
            ],
            [
                'name' => 'Zahle Evening by Berdawni',
                'city' => 'zahle',
                'category' => 'scenic',
                'description' => 'Spend the evening near Berdawni enjoying the atmosphere, lights, and a classic Zahle outing.',
                'location' => 'Berdawni',
                'best_time' => 'evening',
                'duration_estimate' => '1-2 hours',
                'price_type' => 'low',
                'vibe_tags' => ['scenic', 'cozy', 'casual'],
                'occasion_tags' => ['friends', 'family', 'casual'],
            ],
        ];

        foreach ($activities as $activity) {
            $searchText = trim(implode(' ', array_filter([
                "Activity: {$activity['name']}",
                "City: {$activity['city']}",
                "Category: {$activity['category']}",
                "Description: {$activity['description']}",
                "Location: {$activity['location']}",
                "Best time: {$activity['best_time']}",
                "Duration: {$activity['duration_estimate']}",
                "Price: {$activity['price_type']}",
                "Vibe tags: " . implode(', ', $activity['vibe_tags']),
                "Occasion tags: " . implode(', ', $activity['occasion_tags']),
            ])));

            Activity::updateOrCreate(
                [
                    'name' => $activity['name'],
                    'city' => $activity['city'],
                ],
                array_merge($activity, [
                    'search_text' => $searchText,
                ])
            );
        }
    }
}
