<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Activity;

class ActivitiesTableSeeder extends Seeder
{
    public function run(): void
    {
        $activities = [
            // Byblos additions
            [
                'name' => 'Explore Byblos Archaeological Area',
                'city' => 'byblos',
                'category' => 'historical',
                'description' => 'A cultural stop around the archaeological remains with old stones, history, and open sea views nearby.',
                'location' => 'Byblos Archaeological Site',
                'best_time' => 'morning',
                'duration_estimate' => '1-2 hours',
                'price_type' => 'medium',
                'vibe_tags' => ['cultural', 'scenic', 'casual'],
                'occasion_tags' => ['friends', 'family', 'casual'],
            ],
            [
                'name' => 'Byblos Harbor Café Break',
                'city' => 'byblos',
                'category' => 'food',
                'description' => 'A relaxed harbor-side stop for coffee, light food, and a calm coastal atmosphere.',
                'location' => 'Byblos Harbor',
                'best_time' => 'afternoon',
                'duration_estimate' => '1 hour',
                'price_type' => 'low',
                'vibe_tags' => ['cozy', 'relaxing', 'seaside'],
                'occasion_tags' => ['friends', 'date', 'casual'],
            ],
            [
                'name' => 'Byblos Marina Evening Walk',
                'city' => 'byblos',
                'category' => 'scenic',
                'description' => 'An easy evening walk by the marina with lights, sea views, and a soft coastal mood.',
                'location' => 'Byblos Marina',
                'best_time' => 'evening',
                'duration_estimate' => '1 hour',
                'price_type' => 'free',
                'vibe_tags' => ['relaxing', 'romantic', 'scenic'],
                'occasion_tags' => ['date', 'friends', 'casual'],
            ],

            // Beirut additions
            [
                'name' => 'Visit the National Museum of Beirut',
                'city' => 'beirut',
                'category' => 'cultural',
                'description' => 'A strong cultural stop to explore Lebanese history, archaeology, and important artifacts.',
                'location' => 'National Museum of Beirut',
                'best_time' => 'afternoon',
                'duration_estimate' => '1-2 hours',
                'price_type' => 'medium',
                'vibe_tags' => ['cultural', 'casual'],
                'occasion_tags' => ['friends', 'family', 'casual'],
            ],
            [
                'name' => 'Zaitunay Bay Sunset Walk',
                'city' => 'beirut',
                'category' => 'scenic',
                'description' => 'A polished waterfront walk with marina views and one of the nicer sunset moments in Beirut.',
                'location' => 'Zaitunay Bay',
                'best_time' => 'sunset',
                'duration_estimate' => '1 hour',
                'price_type' => 'free',
                'vibe_tags' => ['sunset', 'scenic', 'romantic'],
                'occasion_tags' => ['date', 'casual'],
            ],
            [
                'name' => 'Hamra Street Walk',
                'city' => 'beirut',
                'category' => 'city',
                'description' => 'Explore a lively Beirut street with cafés, shops, and a casual urban atmosphere.',
                'location' => 'Hamra',
                'best_time' => 'evening',
                'duration_estimate' => '1-2 hours',
                'price_type' => 'free',
                'vibe_tags' => ['city', 'lively', 'casual'],
                'occasion_tags' => ['friends', 'casual', 'business'],
            ],

            // Batroun additions
            [
                'name' => 'Batroun Harbor Morning Walk',
                'city' => 'batroun',
                'category' => 'walking',
                'description' => 'A calm early walk around the harbor with fishing boats, sea air, and a peaceful coastal mood.',
                'location' => 'Batroun Harbor',
                'best_time' => 'morning',
                'duration_estimate' => '45 minutes',
                'price_type' => 'free',
                'vibe_tags' => ['relaxing', 'seaside', 'casual'],
                'occasion_tags' => ['friends', 'family', 'casual'],
            ],
            [
                'name' => 'Explore Batroun Phoenician Wall',
                'city' => 'batroun',
                'category' => 'historical',
                'description' => 'A short historical stop to enjoy one of Batroun’s most recognizable heritage spots near the sea.',
                'location' => 'Batroun Phoenician Wall Area',
                'best_time' => 'morning',
                'duration_estimate' => '45 minutes',
                'price_type' => 'free',
                'vibe_tags' => ['cultural', 'scenic', 'casual'],
                'occasion_tags' => ['friends', 'family', 'casual'],
            ],
            [
                'name' => 'Batroun Rooftop Evening',
                'city' => 'batroun',
                'category' => 'nightlife',
                'description' => 'A light nightlife option with music, drinks, and a lively evening atmosphere near the coast.',
                'location' => 'Batroun Rooftop District',
                'best_time' => 'evening',
                'duration_estimate' => '2 hours',
                'price_type' => 'medium',
                'vibe_tags' => ['lively', 'fun', 'nightlife'],
                'occasion_tags' => ['friends', 'night-out'],
            ],

            // Tripoli additions
            [
                'name' => 'Visit Tripoli Citadel',
                'city' => 'tripoli',
                'category' => 'historical',
                'description' => 'A major historical stop with old stone architecture, elevated views, and a classic Tripoli feel.',
                'location' => 'Tripoli Citadel',
                'best_time' => 'morning',
                'duration_estimate' => '1-2 hours',
                'price_type' => 'medium',
                'vibe_tags' => ['cultural', 'historical', 'scenic'],
                'occasion_tags' => ['friends', 'family', 'casual'],
            ],
            [
                'name' => 'Al Mina Seafront Walk',
                'city' => 'tripoli',
                'category' => 'scenic',
                'description' => 'A relaxed coastal walk in Al Mina with open views and a more laid-back side of Tripoli.',
                'location' => 'Al Mina',
                'best_time' => 'sunset',
                'duration_estimate' => '1 hour',
                'price_type' => 'free',
                'vibe_tags' => ['relaxing', 'sunset', 'seaside'],
                'occasion_tags' => ['date', 'friends', 'casual'],
            ],
            [
                'name' => 'Explore a Hidden Tripoli Alley',
                'city' => 'tripoli',
                'category' => 'hidden_gem',
                'description' => 'Discover a quieter part of Tripoli with local details, older streets, and a less touristy feel.',
                'location' => 'Tripoli Old Quarter',
                'best_time' => 'afternoon',
                'duration_estimate' => '1 hour',
                'price_type' => 'free',
                'vibe_tags' => ['hidden_gem', 'cultural', 'casual'],
                'occasion_tags' => ['friends', 'casual'],
            ],

            // Tyre additions
            [
                'name' => 'Tyre Old City Walk',
                'city' => 'tyre',
                'category' => 'historical',
                'description' => 'A cultural walk through older streets and landmarks for a classic Tyre atmosphere.',
                'location' => 'Tyre Old City',
                'best_time' => 'morning',
                'duration_estimate' => '1-2 hours',
                'price_type' => 'free',
                'vibe_tags' => ['cultural', 'casual', 'scenic'],
                'occasion_tags' => ['friends', 'family', 'casual'],
            ],
            [
                'name' => 'Relax at Tyre Beach',
                'city' => 'tyre',
                'category' => 'beach',
                'description' => 'Spend a laid-back afternoon by the sea with sand, sun, and a calm coastal vibe.',
                'location' => 'Tyre Beach',
                'best_time' => 'afternoon',
                'duration_estimate' => '2-3 hours',
                'price_type' => 'low',
                'vibe_tags' => ['beach', 'relaxing', 'seaside'],
                'occasion_tags' => ['friends', 'family', 'casual'],
            ],
            [
                'name' => 'Tyre Harbor Sunset Walk',
                'city' => 'tyre',
                'category' => 'scenic',
                'description' => 'A calm sunset walk near the harbor with open sea views and a romantic coastal feel.',
                'location' => 'Tyre Harbor',
                'best_time' => 'sunset',
                'duration_estimate' => '1 hour',
                'price_type' => 'free',
                'vibe_tags' => ['sunset', 'romantic', 'seaside'],
                'occasion_tags' => ['date', 'casual'],
            ],

            // Jounieh additions
            [
                'name' => 'Jounieh Bay Walk',
                'city' => 'jounieh',
                'category' => 'walking',
                'description' => 'An easy coastal walk around the bay with sea views and a lively Jounieh atmosphere.',
                'location' => 'Jounieh Bay',
                'best_time' => 'morning',
                'duration_estimate' => '1 hour',
                'price_type' => 'free',
                'vibe_tags' => ['seaside', 'relaxing', 'casual'],
                'occasion_tags' => ['friends', 'family', 'casual'],
            ],
            [
                'name' => 'Harissa Scenic Stop',
                'city' => 'jounieh',
                'category' => 'scenic',
                'description' => 'A scenic stop for elevated views over Jounieh and a memorable mountain-to-sea perspective.',
                'location' => 'Harissa',
                'best_time' => 'afternoon',
                'duration_estimate' => '1 hour',
                'price_type' => 'medium',
                'vibe_tags' => ['scenic', 'cultural', 'romantic'],
                'occasion_tags' => ['date', 'friends', 'family'],
            ],
            [
                'name' => 'Jounieh Evening Strip Walk',
                'city' => 'jounieh',
                'category' => 'nightlife',
                'description' => 'A lively evening experience around cafés, music spots, and the energetic Jounieh coast.',
                'location' => 'Jounieh Seafront',
                'best_time' => 'evening',
                'duration_estimate' => '2 hours',
                'price_type' => 'low',
                'vibe_tags' => ['lively', 'fun', 'nightlife'],
                'occasion_tags' => ['friends', 'night-out'],
            ],

            // Saida additions
            [
                'name' => 'Saida Old Souk Walk',
                'city' => 'saida',
                'category' => 'cultural',
                'description' => 'A traditional walk through the souk with local shops, older streets, and everyday city character.',
                'location' => 'Saida Old Souk',
                'best_time' => 'morning',
                'duration_estimate' => '1-2 hours',
                'price_type' => 'free',
                'vibe_tags' => ['cultural', 'casual'],
                'occasion_tags' => ['friends', 'family', 'casual'],
            ],
            [
                'name' => 'Visit Saida Sea Castle',
                'city' => 'saida',
                'category' => 'historical',
                'description' => 'A historical stop by the water with heritage value, sea views, and strong photo potential.',
                'location' => 'Saida Sea Castle',
                'best_time' => 'afternoon',
                'duration_estimate' => '1 hour',
                'price_type' => 'medium',
                'vibe_tags' => ['historical', 'scenic', 'cultural'],
                'occasion_tags' => ['friends', 'family', 'casual'],
            ],
            [
                'name' => 'Saida Corniche Sunset Walk',
                'city' => 'saida',
                'category' => 'scenic',
                'description' => 'A soft seaside walk at sunset with open views and a relaxed South Lebanon coastal mood.',
                'location' => 'Saida Corniche',
                'best_time' => 'sunset',
                'duration_estimate' => '1 hour',
                'price_type' => 'free',
                'vibe_tags' => ['sunset', 'relaxing', 'seaside'],
                'occasion_tags' => ['date', 'friends', 'casual'],
            ],

            // Broumana additions
            [
                'name' => 'Broumana Pine Walk',
                'city' => 'broumana',
                'category' => 'walking',
                'description' => 'A fresh mountain-area walk with trees, cleaner air, and a calm Broumana atmosphere.',
                'location' => 'Broumana Main Road Area',
                'best_time' => 'morning',
                'duration_estimate' => '1 hour',
                'price_type' => 'free',
                'vibe_tags' => ['relaxing', 'scenic', 'casual'],
                'occasion_tags' => ['friends', 'family', 'casual'],
            ],
            [
                'name' => 'Broumana Café Terrace Break',
                'city' => 'broumana',
                'category' => 'food',
                'description' => 'A cozy stop on a terrace for coffee, light food, and a cooler mountain-town vibe.',
                'location' => 'Broumana Center',
                'best_time' => 'afternoon',
                'duration_estimate' => '1 hour',
                'price_type' => 'low',
                'vibe_tags' => ['cozy', 'relaxing', 'casual'],
                'occasion_tags' => ['friends', 'date', 'casual'],
            ],
            [
                'name' => 'Broumana Evening Stroll',
                'city' => 'broumana',
                'category' => 'city',
                'description' => 'A simple evening walk through Broumana for lights, cafés, and a relaxed social atmosphere.',
                'location' => 'Broumana Main Street',
                'best_time' => 'evening',
                'duration_estimate' => '1 hour',
                'price_type' => 'free',
                'vibe_tags' => ['cozy', 'city', 'casual'],
                'occasion_tags' => ['friends', 'casual'],
            ],

            // Zahle additions
            [
                'name' => 'Zahle Riverside Walk',
                'city' => 'zahle',
                'category' => 'walking',
                'description' => 'A relaxed walk by the river with local energy, open-air seating, and a classic Zahle feel.',
                'location' => 'Berdawni Area',
                'best_time' => 'morning',
                'duration_estimate' => '1 hour',
                'price_type' => 'free',
                'vibe_tags' => ['relaxing', 'casual', 'scenic'],
                'occasion_tags' => ['friends', 'family', 'casual'],
            ],
            [
                'name' => 'Explore Zahle Old Streets',
                'city' => 'zahle',
                'category' => 'cultural',
                'description' => 'A cultural walk through older parts of Zahle with local charm and a slower atmosphere.',
                'location' => 'Old Zahle',
                'best_time' => 'afternoon',
                'duration_estimate' => '1-2 hours',
                'price_type' => 'free',
                'vibe_tags' => ['cultural', 'casual', 'hidden_gem'],
                'occasion_tags' => ['friends', 'casual'],
            ],
            [
                'name' => 'Zahle Evening by Berdawni',
                'city' => 'zahle',
                'category' => 'scenic',
                'description' => 'Spend the evening near Berdawni enjoying the atmosphere, lights, and a classic Zahle outing.',
                'location' => 'Berdawni',
                'best_time' => 'evening',
                'duration_estimate' => '1-2 hours',
                'price_type' => 'low',
                'vibe_tags' => ['scenic', 'cozy', 'casual'],
                'occasion_tags' => ['friends', 'family', 'casual'],
            ],

            // Extra variety to reduce repeated activity recommendations
            [
                'name' => 'Byblos Old Souk Browse',
                'city' => 'byblos',
                'category' => 'shopping',
                'description' => 'A relaxed browse through stone lanes, small shops, souvenirs, and local snacks near the old town.',
                'location' => 'Byblos Old Souk',
                'best_time' => 'afternoon',
                'duration_estimate' => '1-2 hours',
                'price_type' => 'free',
                'vibe_tags' => ['local', 'cultural', 'casual'],
                'occasion_tags' => ['friends', 'family', 'casual'],
            ],
            [
                'name' => 'Byblos Castle View Stop',
                'city' => 'byblos',
                'category' => 'historical',
                'description' => 'A short heritage stop around the castle area with old walls, sea views, and easy photo moments.',
                'location' => 'Byblos Castle',
                'best_time' => 'morning',
                'duration_estimate' => '1 hour',
                'price_type' => 'medium',
                'vibe_tags' => ['historical', 'scenic', 'cultural'],
                'occasion_tags' => ['friends', 'family', 'casual'],
            ],
            [
                'name' => 'Byblos Beach Slow Afternoon',
                'city' => 'byblos',
                'category' => 'beach',
                'description' => 'A simple beach break for sea air, slow pacing, and a calm coastal afternoon near Byblos.',
                'location' => 'Byblos Beach Area',
                'best_time' => 'afternoon',
                'duration_estimate' => '2-3 hours',
                'price_type' => 'medium',
                'vibe_tags' => ['beach', 'relaxing', 'seaside'],
                'occasion_tags' => ['date', 'friends', 'family'],
            ],
            [
                'name' => 'Byblos Sunset Photo Stop',
                'city' => 'byblos',
                'category' => 'scenic',
                'description' => 'A quiet sunset stop near the harbor and sea walls for photos and a slower end to the day.',
                'location' => 'Byblos Harbor Viewpoint',
                'best_time' => 'sunset',
                'duration_estimate' => '45 minutes',
                'price_type' => 'free',
                'vibe_tags' => ['sunset', 'romantic', 'scenic'],
                'occasion_tags' => ['date', 'friends', 'casual'],
            ],

            [
                'name' => 'Beirut Corniche Morning Walk',
                'city' => 'beirut',
                'category' => 'walking',
                'description' => 'A fresh morning walk along the seafront with open views, local movement, and an easy city pace.',
                'location' => 'Beirut Corniche',
                'best_time' => 'morning',
                'duration_estimate' => '1 hour',
                'price_type' => 'free',
                'vibe_tags' => ['seaside', 'active', 'casual'],
                'occasion_tags' => ['solo', 'friends', 'family'],
            ],
            [
                'name' => 'Raouche Rocks Sunset Stop',
                'city' => 'beirut',
                'category' => 'scenic',
                'description' => 'A classic Beirut sunset viewpoint with sea cliffs, open air, and an easy photo stop.',
                'location' => 'Raouche',
                'best_time' => 'sunset',
                'duration_estimate' => '45 minutes',
                'price_type' => 'free',
                'vibe_tags' => ['sunset', 'scenic', 'romantic'],
                'occasion_tags' => ['date', 'friends', 'casual'],
            ],
            [
                'name' => 'Gemmayzeh Art Street Walk',
                'city' => 'beirut',
                'category' => 'art',
                'description' => 'A casual walk through creative streets with murals, small galleries, cafes, and city character.',
                'location' => 'Gemmayzeh',
                'best_time' => 'afternoon',
                'duration_estimate' => '1-2 hours',
                'price_type' => 'free',
                'vibe_tags' => ['artsy', 'city', 'lively'],
                'occasion_tags' => ['friends', 'date', 'casual'],
            ],
            [
                'name' => 'Sursock Museum Culture Stop',
                'city' => 'beirut',
                'category' => 'cultural',
                'description' => 'A refined culture stop for art, architecture, and a quieter indoor break in the city.',
                'location' => 'Sursock Museum',
                'best_time' => 'afternoon',
                'duration_estimate' => '1-2 hours',
                'price_type' => 'medium',
                'vibe_tags' => ['cultural', 'artsy', 'quiet'],
                'occasion_tags' => ['solo', 'date', 'friends'],
            ],

            [
                'name' => 'Batroun Old Souk Lemonade Stop',
                'city' => 'batroun',
                'category' => 'food',
                'description' => 'A light local stop in the old souk for lemonade, small shops, and an easy coastal-town feel.',
                'location' => 'Batroun Old Souk',
                'best_time' => 'afternoon',
                'duration_estimate' => '1 hour',
                'price_type' => 'low',
                'vibe_tags' => ['local', 'refreshing', 'casual'],
                'occasion_tags' => ['friends', 'family', 'casual'],
            ],
            [
                'name' => 'Batroun Seaside Bike Ride',
                'city' => 'batroun',
                'category' => 'active',
                'description' => 'A breezy seaside ride for travelers who want movement, sea views, and a more active coastal plan.',
                'location' => 'Batroun Seaside Road',
                'best_time' => 'morning',
                'duration_estimate' => '1-2 hours',
                'price_type' => 'medium',
                'vibe_tags' => ['active', 'seaside', 'fun'],
                'occasion_tags' => ['friends', 'couple', 'casual'],
            ],
            [
                'name' => 'Batroun Beach Swim Break',
                'city' => 'batroun',
                'category' => 'beach',
                'description' => 'A relaxed swim and beach break for a sunny afternoon close to Batroun coastal spots.',
                'location' => 'Batroun Beach Area',
                'best_time' => 'afternoon',
                'duration_estimate' => '2-3 hours',
                'price_type' => 'medium',
                'vibe_tags' => ['beach', 'relaxing', 'sunny'],
                'occasion_tags' => ['friends', 'date', 'family'],
            ],
            [
                'name' => 'Batroun Sunset Photo Walk',
                'city' => 'batroun',
                'category' => 'scenic',
                'description' => 'A soft sunset walk through seaside corners, old stone details, and calm photo spots.',
                'location' => 'Batroun Seaside',
                'best_time' => 'sunset',
                'duration_estimate' => '1 hour',
                'price_type' => 'free',
                'vibe_tags' => ['sunset', 'romantic', 'scenic'],
                'occasion_tags' => ['date', 'friends', 'casual'],
            ],

            [
                'name' => 'Tripoli Soap Souk Visit',
                'city' => 'tripoli',
                'category' => 'cultural',
                'description' => 'A heritage stop through old soap shops and market corners with a strong local character.',
                'location' => 'Tripoli Old Souks',
                'best_time' => 'morning',
                'duration_estimate' => '1 hour',
                'price_type' => 'low',
                'vibe_tags' => ['cultural', 'local', 'heritage'],
                'occasion_tags' => ['friends', 'family', 'casual'],
            ],
            [
                'name' => 'Tripoli Sweet Trail',
                'city' => 'tripoli',
                'category' => 'food',
                'description' => 'A casual food stop focused on Tripoli sweets, bakeries, and a warm local tasting experience.',
                'location' => 'Tripoli Center',
                'best_time' => 'afternoon',
                'duration_estimate' => '1 hour',
                'price_type' => 'low',
                'vibe_tags' => ['foodie', 'local', 'casual'],
                'occasion_tags' => ['friends', 'family', 'casual'],
            ],
            [
                'name' => 'Al Mina Old Port Coffee Stop',
                'city' => 'tripoli',
                'category' => 'food',
                'description' => 'A quiet coffee break near the old port with sea air and a slower North Lebanon mood.',
                'location' => 'Al Mina Old Port',
                'best_time' => 'afternoon',
                'duration_estimate' => '1 hour',
                'price_type' => 'low',
                'vibe_tags' => ['quiet', 'seaside', 'local'],
                'occasion_tags' => ['solo', 'date', 'friends'],
            ],
            [
                'name' => 'Tripoli Rachid Karami Fair Walk',
                'city' => 'tripoli',
                'category' => 'architecture',
                'description' => 'A modernist architecture walk for travelers interested in design, history, and quieter open spaces.',
                'location' => 'Rachid Karami International Fair',
                'best_time' => 'morning',
                'duration_estimate' => '1-2 hours',
                'price_type' => 'free',
                'vibe_tags' => ['architecture', 'quiet', 'cultural'],
                'occasion_tags' => ['solo', 'friends', 'casual'],
            ],

            [
                'name' => 'Tyre Roman Hippodrome Visit',
                'city' => 'tyre',
                'category' => 'historical',
                'description' => 'A strong heritage stop around Roman remains and open archaeological scenery in Tyre.',
                'location' => 'Tyre Roman Hippodrome',
                'best_time' => 'morning',
                'duration_estimate' => '1-2 hours',
                'price_type' => 'medium',
                'vibe_tags' => ['historical', 'cultural', 'scenic'],
                'occasion_tags' => ['friends', 'family', 'casual'],
            ],
            [
                'name' => 'Tyre Fishing Port Walk',
                'city' => 'tyre',
                'category' => 'walking',
                'description' => 'A relaxed walk near fishing boats, small streets, and the calm rhythm of the old port.',
                'location' => 'Tyre Old Port',
                'best_time' => 'morning',
                'duration_estimate' => '1 hour',
                'price_type' => 'free',
                'vibe_tags' => ['seaside', 'local', 'relaxing'],
                'occasion_tags' => ['solo', 'friends', 'family'],
            ],
            [
                'name' => 'Tyre Souk Snack Stop',
                'city' => 'tyre',
                'category' => 'food',
                'description' => 'A light local snack stop through the souk for simple food, small shops, and local color.',
                'location' => 'Tyre Souk',
                'best_time' => 'afternoon',
                'duration_estimate' => '1 hour',
                'price_type' => 'low',
                'vibe_tags' => ['foodie', 'local', 'casual'],
                'occasion_tags' => ['friends', 'family', 'casual'],
            ],
            [
                'name' => 'Tyre Coastal Photo Walk',
                'city' => 'tyre',
                'category' => 'scenic',
                'description' => 'A quiet coastal walk for sea photos, old-town edges, and a soft sunset atmosphere.',
                'location' => 'Tyre Coast',
                'best_time' => 'sunset',
                'duration_estimate' => '1 hour',
                'price_type' => 'free',
                'vibe_tags' => ['sunset', 'scenic', 'quiet'],
                'occasion_tags' => ['date', 'friends', 'casual'],
            ],

            [
                'name' => 'Jounieh Teleferique Ride',
                'city' => 'jounieh',
                'category' => 'scenic',
                'description' => 'A classic ride above Jounieh with bay views and a memorable mountain-to-sea perspective.',
                'location' => 'Jounieh Teleferique',
                'best_time' => 'morning',
                'duration_estimate' => '1-2 hours',
                'price_type' => 'medium',
                'vibe_tags' => ['scenic', 'adventure', 'romantic'],
                'occasion_tags' => ['date', 'family', 'friends'],
            ],
            [
                'name' => 'Kaslik Cafe Stretch',
                'city' => 'jounieh',
                'category' => 'food',
                'description' => 'A casual cafe and dessert stop around Kaslik for a lighter afternoon plan.',
                'location' => 'Kaslik',
                'best_time' => 'afternoon',
                'duration_estimate' => '1 hour',
                'price_type' => 'low',
                'vibe_tags' => ['cozy', 'casual', 'city'],
                'occasion_tags' => ['friends', 'date', 'casual'],
            ],
            [
                'name' => 'Jounieh Waterfront Sunset Stop',
                'city' => 'jounieh',
                'category' => 'scenic',
                'description' => 'A soft waterfront stop for sunset views over the bay and a relaxed evening start.',
                'location' => 'Jounieh Waterfront',
                'best_time' => 'sunset',
                'duration_estimate' => '1 hour',
                'price_type' => 'free',
                'vibe_tags' => ['sunset', 'romantic', 'seaside'],
                'occasion_tags' => ['date', 'friends', 'casual'],
            ],
            [
                'name' => 'Jounieh Night Drive View',
                'city' => 'jounieh',
                'category' => 'scenic',
                'description' => 'An evening viewpoint-style plan for city lights, bay views, and a calm night mood.',
                'location' => 'Harissa View Road',
                'best_time' => 'evening',
                'duration_estimate' => '1 hour',
                'price_type' => 'free',
                'vibe_tags' => ['nightlife', 'scenic', 'romantic'],
                'occasion_tags' => ['date', 'friends', 'casual'],
            ],

            [
                'name' => 'Khan El Franj Courtyard Visit',
                'city' => 'saida',
                'category' => 'historical',
                'description' => 'A calm heritage stop inside an old courtyard space with architecture and Saida old-city context.',
                'location' => 'Khan El Franj',
                'best_time' => 'morning',
                'duration_estimate' => '1 hour',
                'price_type' => 'free',
                'vibe_tags' => ['historical', 'quiet', 'cultural'],
                'occasion_tags' => ['friends', 'family', 'casual'],
            ],
            [
                'name' => 'Saida Soap Museum Stop',
                'city' => 'saida',
                'category' => 'cultural',
                'description' => 'A focused cultural visit about local soap-making heritage in the old city.',
                'location' => 'Saida Soap Museum',
                'best_time' => 'afternoon',
                'duration_estimate' => '1 hour',
                'price_type' => 'medium',
                'vibe_tags' => ['cultural', 'heritage', 'quiet'],
                'occasion_tags' => ['solo', 'friends', 'family'],
            ],
            [
                'name' => 'Saida Old Port View',
                'city' => 'saida',
                'category' => 'scenic',
                'description' => 'A simple old-port viewpoint for sea air, boats, and a softer side of Saida.',
                'location' => 'Saida Old Port',
                'best_time' => 'sunset',
                'duration_estimate' => '45 minutes',
                'price_type' => 'free',
                'vibe_tags' => ['seaside', 'scenic', 'relaxing'],
                'occasion_tags' => ['date', 'friends', 'casual'],
            ],
            [
                'name' => 'Saida Local Sweets Stop',
                'city' => 'saida',
                'category' => 'food',
                'description' => 'A short stop for local sweets and coffee before or after exploring the old city.',
                'location' => 'Saida Old City',
                'best_time' => 'afternoon',
                'duration_estimate' => '45 minutes',
                'price_type' => 'low',
                'vibe_tags' => ['foodie', 'local', 'casual'],
                'occasion_tags' => ['friends', 'family', 'casual'],
            ],

            [
                'name' => 'Broumana Sunset Viewpoint',
                'city' => 'broumana',
                'category' => 'scenic',
                'description' => 'A calm viewpoint stop for cooler air, mountain-town views, and a relaxed sunset mood.',
                'location' => 'Broumana Viewpoint',
                'best_time' => 'sunset',
                'duration_estimate' => '45 minutes',
                'price_type' => 'free',
                'vibe_tags' => ['sunset', 'mountain', 'quiet'],
                'occasion_tags' => ['date', 'friends', 'casual'],
            ],
            [
                'name' => 'Broumana Forest Picnic',
                'city' => 'broumana',
                'category' => 'nature',
                'description' => 'A simple nature break with trees, cooler weather, and a picnic-friendly mountain feel.',
                'location' => 'Broumana Pine Area',
                'best_time' => 'morning',
                'duration_estimate' => '2 hours',
                'price_type' => 'free',
                'vibe_tags' => ['nature', 'quiet', 'family'],
                'occasion_tags' => ['family', 'friends', 'casual'],
            ],
            [
                'name' => 'Broumana Local Market Browse',
                'city' => 'broumana',
                'category' => 'shopping',
                'description' => 'A light browse through local shops and small stops for an easy afternoon in town.',
                'location' => 'Broumana Center',
                'best_time' => 'afternoon',
                'duration_estimate' => '1 hour',
                'price_type' => 'free',
                'vibe_tags' => ['local', 'casual', 'cozy'],
                'occasion_tags' => ['friends', 'family', 'casual'],
            ],
            [
                'name' => 'Dhour Choueir View Detour',
                'city' => 'broumana',
                'category' => 'scenic',
                'description' => 'A nearby mountain-view detour for travelers who want a quieter scenic stop outside the main town.',
                'location' => 'Dhour Choueir Area',
                'best_time' => 'afternoon',
                'duration_estimate' => '1-2 hours',
                'price_type' => 'free',
                'vibe_tags' => ['mountain', 'quiet', 'scenic'],
                'occasion_tags' => ['date', 'friends', 'casual'],
            ],

            [
                'name' => 'Berdawni Food Promenade',
                'city' => 'zahle',
                'category' => 'food',
                'description' => 'A food-focused walk around Berdawni for local flavors, outdoor seating, and classic Zahle energy.',
                'location' => 'Berdawni',
                'best_time' => 'lunch',
                'duration_estimate' => '1-2 hours',
                'price_type' => 'medium',
                'vibe_tags' => ['foodie', 'local', 'lively'],
                'occasion_tags' => ['friends', 'family', 'casual'],
            ],
            [
                'name' => 'Zahle Wine Cave Visit',
                'city' => 'zahle',
                'category' => 'wine',
                'description' => 'A refined wine stop for travelers interested in Bekaa wine culture and a slower afternoon plan.',
                'location' => 'Zahle Wine Area',
                'best_time' => 'afternoon',
                'duration_estimate' => '1-2 hours',
                'price_type' => 'premium',
                'vibe_tags' => ['wine', 'romantic', 'cultural'],
                'occasion_tags' => ['date', 'friends', 'couple'],
            ],
            [
                'name' => 'Taanayel Lake Nature Break',
                'city' => 'zahle',
                'category' => 'nature',
                'description' => 'A nearby nature break with lake views, fresh air, and a peaceful Bekaa Valley atmosphere.',
                'location' => 'Taanayel Lake',
                'best_time' => 'morning',
                'duration_estimate' => '1-2 hours',
                'price_type' => 'low',
                'vibe_tags' => ['nature', 'quiet', 'scenic'],
                'occasion_tags' => ['family', 'friends', 'casual'],
            ],
            [
                'name' => 'Zahle Old Bridge Photo Stop',
                'city' => 'zahle',
                'category' => 'scenic',
                'description' => 'A short photo stop around older streets and bridge views for a gentle heritage feel.',
                'location' => 'Old Zahle Bridge Area',
                'best_time' => 'sunset',
                'duration_estimate' => '45 minutes',
                'price_type' => 'free',
                'vibe_tags' => ['scenic', 'cultural', 'quiet'],
                'occasion_tags' => ['friends', 'date', 'casual'],
            ],
        ];

        foreach ($activities as $activity) {
            $searchText = trim(implode(' ', array_filter([
                "Activity: {$activity['name']}",
                "City: {$activity['city']}",
                "Category: {$activity['category']}",
                "Description: {$activity['description']}",
                "Location: {$activity['location']}",
                "Best time: {$activity['best_time']}",
                "Duration: {$activity['duration_estimate']}",
                "Price: {$activity['price_type']}",
                "Vibe tags: " . implode(', ', $activity['vibe_tags']),
                "Occasion tags: " . implode(', ', $activity['occasion_tags']),
            ])));

            Activity::updateOrCreate(
                [
                    'name' => $activity['name'],
                    'city' => $activity['city'],
                ],
                array_merge($activity, [
                    'search_text' => $searchText,
                ])
            );
        }
    }
}
